version: '3'

volumes:
    pgdata:
        driver: local
services:
    nginx:
        restart: always
        image: nginx:latest
        expose:
          - 8080
        ports:
          - "80:8080"
# монтируем только те директории, в которых лежит статика, т.к. nginx с динамикой не будет работать. Также директорию с логами и файл настройки, который мы подготовили.
        volumes:
            - ./assistant/static:/srv/www/assistant/static
            - ./assistant/media:/srv/www/assistant/media
            - ./assistant/logs:/srv/www/assistant/logs
            - ./docker/nginx:/etc/nginx/conf.d
# и nginx зависит от контейнера python. Т.е. python должен быть запущен первым
        depends_on:
            - python
    python:
        restart: always
        build:
            context: .
            dockerfile: docker/python/Dockerfile
        volumes:
            - ./assistant:/srv/www/assistant
        expose:
          - 8000
        ports:
            - 8000:8000
        env_file:
          - .env
        command: "gunicorn -c gunicorn.py assistant.wsgi"
    postgres:
        image: postgres:9.3.22
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: elena
            POSTGRES_PASSWORD: 3414269
            POSTGRES_DB: assistant
            PGDATA: /var/lib/postgresql/data
        volumes:
            - pgdata:/var/lib/postgresql/data
